### ISSUE TITLE
Invalid date in Firefox

### ISSUE THREAD

**Issue by kja-xyt** [KeshiaRose/latest-date-updater#1]
There is an issue with the plugin in Firefox.  The conversion to Date (index.html, line: 211):
```
dates.push(new Date(dataValue[fieldIndex].value + "Z"));
```
is not working correctly. Should be something like:
dates.push(new Date(dataValue[fieldIndex].value + "T00:00:00Z"));

Firefox console output:
![image](https://user-images.githubusercontent.com/16593018/62027185-54cb2900-b1dd-11e9-892a-587170559879.png)

**Comment by KeshiaRose** [comment]
Hi @kja-xyt,

This repo is deprecated, please go to the [Extension Gallery](https://extensiongallery.tableau.com/products/28) for the latest official version.

Take care,
Keshia
